version: '3.8'
name: 'Backend Integration Test'
services:
  db:
    image: mariadb:10.5.27
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
