export { default as userService } from "./user.service";
export { default as campService } from "./camp.service";
export { default as authService } from "./auth.service";
export { default as tokenService } from "./token.service";
export { default as emailService } from "./email.service";
export { default as campManagerService } from "./campManager.serivce";
export { default as registrationService } from "./registration.service";
export { default as templateService } from "./template.service";
export { default as fileService } from "./file.service";
