export default {
  locale: 'en',
  title: '{camp.name}',
  description: '{camp.startAtDate} - {camp.endAtDate}',
  logoHeight: '80px',
  logoPosition: 'right',
  completedHtml: {
    en: '<h3>Thank you for your registration!</h3><p style="font-size: 18px">You should receive a confirmation email shortly.</p>',
    de: '<h3>Vielen Dank für deine Anmeldung!</h3><p style="font-size: 18px">Du solltest in Kürze eine Bestätigungsmail erhalten.</p>',
    fr: '<h3>Merci de t\'inscrire!</h3><p style="font-size: 18px">Tu devrais recevoir un e-mail de confirmation dans les plus brefs délais.</p>',
    pl: '<h3>Dziękujemy za rejestrację!</h3><p style="font-size: 18px">Wkrótce powinieneś/powinnaś otrzymać e-mail z potwierdzeniem.</p>',
    cs: '<h3>Děkujeme za registraci!</h3><p style="font-size: 18px">Brzy by ti měl přijít potvrzovací e-mail.</p>',
    default:
      '<h3>Thank you for your registration!</h3><p style="font-size: 18px">You should receive a confirmation email shortly.</p>',
  },
  pages: [
    {
      name: 'p_overview',
      title: {
        en: 'Information',
        de: 'Informationen',
        fr: 'Informations',
        pl: 'Informacje',
        cs: 'Informace',
        default: 'Information',
      },
      elements: [
        {
          type: 'expression',
          name: 'i_date',
          title: {
            en: 'Date',
            de: 'Datum',
            fr: 'Date',
            pl: 'Data',
            cs: 'Datum',
          },
          description: {
            en: '{camp.startAtDate} until {camp.endAtDate}',
            de: '{camp.startAtDate} bis {camp.endAtDate}',
            fr: '{camp.startAtDate} au {camp.endAtDate}',
            pl: '{camp.startAtDate} do {camp.endAtDate}',
            cs: '{camp.startAtDate} až {camp.endAtDate}',
            default: '{camp.startAtDate} until {camp.endAtDate}',
          },
        },
        {
          type: 'expression',
          name: 'i_location',
          title: {
            en: 'Location',
            de: 'Ort',
            fr: 'Lieu',
            pl: 'Miejsce',
            cs: 'Místo',
            default: 'Location',
          },
          description: '{camp.location}',
        },
        {
          type: 'expression',
          name: 'i_price',
          title: {
            en: 'Price',
            de: 'Preis',
            fr: 'Prix',
            pl: 'Cena',
            cs: 'Cena',
            default: 'Price',
          },
          description: '{camp.price} €',
          currency: 'EUR',
        },
        {
          type: 'role',
          name: 'role',
          title: {
            en: 'Role',
            fr: 'Rôle',
            de: 'Rolle',
            pl: 'Rola',
            cs: 'Role',
            default: 'Role',
          },
          defaultValue: 'participant',
          isRequired: true,
          campDataType: 'role',
        },
      ],
    },
    {
      name: 'p_personal_information',
      title: {
        en: 'Personal Information',
        de: 'Persönliche Informationen',
        fr: 'Informations personnelles',
        pl: 'Dane osobowe',
        cs: 'Osobní informace',
        default: 'Personal Information',
      },
      elements: [
        {
          type: 'text',
          name: 'first_name',
          title: {
            en: 'First Name',
            de: 'Vorname',
            fr: 'Prénom',
            pl: 'Imię',
            cs: 'Jméno',
            default: 'First Name',
          },
          isRequired: true,
          campDataType: 'first_name',
          autocomplete: 'given-name',
        },
        {
          type: 'text',
          name: 'last_name',
          startWithNewLine: false,
          title: {
            en: 'Last Name',
            de: 'Nachname',
            fr: 'Nom de Famille',
            pl: 'Nazwisko',
            cs: 'Příjmení',
            default: 'Last Name',
          },
          isRequired: true,
          campDataType: 'last_name',
          autocomplete: 'family-name',
        },
        {
          type: 'dropdown',
          name: 'gender',
          title: {
            en: 'Gender',
            de: 'Geschlecht',
            fr: 'Sexe',
            pl: 'Płeć',
            cs: 'Pohlaví',
            default: 'Gender',
          },
          choices: [
            {
              value: 'm',
              text: {
                en: 'male',
                de: 'männlich',
                fr: 'masculin',
                pl: 'mężczyzna',
                cs: 'muž',
                default: 'male',
              },
            },
            {
              value: 'f',
              text: {
                en: 'female',
                de: 'weiblich',
                fr: 'féminin',
                pl: 'kobieta',
                cs: 'žena',
                default: 'female',
              },
            },
          ],
          campDataType: 'gender',
          autocomplete: 'sex',
        },
        {
          type: 'text',
          name: 'date_of_birth',
          title: {
            en: 'Date of Birth',
            de: 'Geburtsdatum',
            fr: 'Date de naissance',
            pl: 'Data urodzenia',
            cs: 'Datum narození',
            default: 'Date of Birth',
          },
          campDataType: 'date_of_birth',
          inputType: 'date',
          autocomplete: 'bday',
          placeholder: {
            en: 'dd.mm.yyyy',
            de: 'tt.mm.jjjj',
            fr: 'jj.mm.aaaa',
            pl: 'dd.mm.rrrr',
            cs: 'dd.mm.rrrr',
            default: 'dd.mm.yyyy',
          },
        },
        {
          type: 'country',
          name: 'country',
          visibleIf: 'count({camp.countries}) > 1',
          requiredIf: 'count({camp.countries}) > 1',
          title: {
            en: 'Country',
            de: 'Land',
            fr: 'Pays',
            pl: 'Kraj',
            cs: 'Země',
            default: 'Country',
          },
          campDataType: 'country',
        },
      ],
    },
    {
      name: 'p_contact',
      title: {
        en: 'Contact Information',
        de: 'Kontaktinformationen',
        fr: 'Coordonnées',
        pl: 'Dane kontaktowe',
        cs: 'Kontaktní údaje',
        default: 'Contact Information',
      },
      elements: [
        {
          type: 'text',
          name: 'email',
          title: {
            en: 'E-Mail',
            de: 'E-Mail',
            fr: 'E-Mail',
            pl: 'E-mail',
            cs: 'E-mail',
            default: 'E-Mail',
          },
          isRequired: true,
          campDataType: 'email',
          inputType: 'email',
          autocomplete: 'email',
        },
        {
          type: 'text',
          name: 'phone_number',
          title: {
            en: 'Phone Number',
            de: 'Telefonnummer',
            fr: 'Numéro de téléphone',
            pl: 'Numer telefonu',
            cs: 'Telefonní číslo',
            default: 'Phone Number',
          },
          inputType: 'tel',
          autocomplete: 'tel',
        },
        {
          type: 'boolean',
          name: 'waiting_list',
          visible: false,
          visibleIf: '{waitingList} = true',
          title: {
            en: 'Waiting list',
            de: 'Warteliste',
            fr: "Liste d'attente",
            pl: 'Lista oczekujących',
            cs: 'Čekací listina',
            default: 'Waiting list',
          },
          description: {
            en: 'Unfortunately, all places for participants from this country are already taken. However, you can put your name on the waiting list. We will inform you as soon as a place becomes available.',
            de: 'Leider sind bereits alle Plätze für Teilnehmer aus diesem Land belegt. Du kannst dich aber auf die Warteliste setzen. Wir informieren dich, sobald ein Platz frei wird.',
            fr: "Malheureusement, toutes les places pour les participants de ce pays sont déjà prises. Tu peux toutefois t'inscrire sur la liste d'attente. Nous t'informerons dès qu'une place se libérera.",
            pl: 'Niestety wszystkie miejsca dla uczestników z tego kraju są już zajęte. Możesz jednak zapisać się na listę oczekujących. Poinformujemy Cię, gdy tylko zwolni się miejsce.',
            cs: 'Bohužel jsou všechna místa pro účastníky z této země již obsazena. Můžeš se ale zapsat na čekací listinu. Dáme ti vědět, jakmile se uvolní místo.',
            default:
              'Unfortunately, all places for participants from this country are already taken. However, you can put your name on the waiting list. We will inform you as soon as a place becomes available.',
          },
          correctAnswer: true,
          isRequired: true,
          validators: [
            {
              type: 'expression',
              text: {
                en: 'Please confirm that you wish to be on the waiting list',
                de: 'Bitte bestätige, dass du auf die Warteliste möchtest',
                fr: "Confirme que tu souhaites être sur la liste d'attente",
                pl: 'Potwierdź, że chcesz znaleźć się na liście oczekujących',
                cs: 'Potvrď, že chceš být na čekací listině',
                default:
                  "Confirme que tu souhaites être sur la liste d'attente",
              },
              expression: '{waiting_list} = true',
            },
          ],
        },
      ],
    },
    {
      name: 'p_consent',
      title: {
        en: 'Consents',
        fr: 'Approbations',
        de: 'Zustimmung',
        pl: 'Zgody',
        cs: 'Souhlasy',
        default: 'Consents',
      },
      elements: [
        {
          type: 'boolean',
          name: 'consent_general_terms_and_conditions',
          title: {
            en: 'I have read the [General Terms and Conditions]({_file.toc}) and agree to them.',
            de: 'Ich habe die [allgemeinen Geschäftsbedingungen]({_file.toc}) gelesen und stimme diesen zu.',
            fr: "J'ai lu et j'accepte les [conditions générales]({_file.toc}).",
            pl: 'Przeczytałem/łam [regulamin / warunki uczestnictwa]({_file.toc}) i je akceptuję.',
            cs: 'Přečetl/a jsem si [obchodní podmínky]({_file.toc}) a souhlasím s nimi.',
            default:
              'I have read the [General Terms and Conditions]({_file.toc}) and agree to them.',
          },
          correctAnswer: true,
          isRequired: true,
          validators: [
            {
              type: 'expression',
              text: {
                en: 'You must agree to our terms and conditions in order to participate!',
                de: 'Du musst unseren AGB zustimmen, um teilnehmen zu können!',
                fr: 'Tu dois accepter nos conditions générales pour pouvoir participer !',
                pl: 'Aby wziąć udział, musisz zaakceptować nasze warunki!',
                cs: 'Pro účast musíš souhlasit s našimi podmínkami!',
                default:
                  'You must agree to our terms and conditions in order to participate!',
              },
              expression: '{consent_general_terms_and_conditions} = true',
            },
          ],
        },
        {
          type: 'boolean',
          name: 'consent_privacy',
          title: {
            en: 'I agree that photographs of {first_name} {last_name} may be taken and made available to the organizer for media coverage and advertising.',
            de: 'Ich stimme zu, dass von {first_name} {last_name} Aufnahmen erstellt werden dürfen und dem Veranstalter für Berichterstattung und Werbezwecke zur Verfügung gestellt werden.',
            fr: "J'accepte que des photos de {first_name} {last_name} soient prises et mises à la disposition de l'organisateur à des fins de reportage et de publicité.",
            pl: 'Wyrażam zgodę na wykonywanie zdjęć {first_name} {last_name} oraz ich udostępnianie organizatorowi w celach relacji medialnych i promocyjnych.',
            cs: 'Souhlasím s pořízením fotografií {first_name} {last_name} a jejich poskytnutím pořadateli pro mediální prezentaci a propagační účely.',
            default:
              'I agree that photographs of {first_name} {last_name} may be taken and made available to the organizer for media coverage and advertising.',
          },
          description: {
            en: 'Consent is voluntary and can be revoked at any time without giving reasons.',
            de: 'Die Zustimmung ist freiwillig und kann jederzeit ohne Angabe von Gründen widerrufen werden.',
            fr: 'Le consentement est volontaire et peut être retiré à tout moment sans justification.',
            pl: 'Zgoda jest dobrowolna i może zostać w każdej chwili odwołana bez podania przyczyny.',
            cs: 'Souhlas je dobrovolný a lze jej kdykoli bez udání důvodu odvolat.',
            default:
              'Consent is voluntary and can be revoked at any time without giving reasons.',
          },
        },
      ],
    },
  ],
  calculatedValues: [
    {
      name: 'waitingList',
      expression: 'isWaitingList({camp.freePlaces}, {country})',
    },
  ],
  showProgressBar: true,
  progressBarLocation: 'bottom',
  completeText: {
    en: 'Complete Registration',
    de: 'Anmeldung abschließen',
    fr: "Finaliser l'inscription",
    pl: 'Zakończ rejestrację',
    cs: 'Dokončit registraci',
    default: 'Complete Registration',
  },
  headerView: 'advanced',
  widthMode: 'static',
};
