version: '3.8'
services:
  db:
    image: mariadb:10.5.27
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_TCP_PORT: 3308
    ports:
      - '3308:3308'
    volumes:
      - db:/var/lib/mysql
  mail:
    image: maildev/maildev:latest
    restart: on-failure
    ports:
      - '1081:1081'
      - '1026:1026'
    environment:
      MAILDEV_SMTP_PORT: '1026'
      MAILDEV_WEB_PORT: '1081'
      MAILDEV_INCOMING_USER: 'user'
      MAILDEV_INCOMING_PASS: 'password'
volumes:
  db:
    driver: local
