// TODO Set file IDs
import config from '#config/index';

const host = config.origin;

export default {
  locale: 'de',
  title: '{camp.name}',
  description: '{camp.startAtDate} - {camp.endAtDate}',
  logoWidth: 'auto',
  logoHeight: '80px',
  logoPosition: 'right',
  completedHtml: {
    en: '<h3>Thank you for your registration!</h3><p stype="font-size: 18px">You should receive a confirmation email shortly.</p>',
    de: '<h3>Vielen Dank für deine Anmeldung!</h3><p stype="font-size: 18px">Du solltest in kurze eine Bestätigungsmail erhalten.</p>',
    fr: '<h3>Merci de t\'inscrire!</h3><p stype="font-size : 18px">Tu devrais recevoir un e-mail de confirmation dans les plus brefs délais.</p>',
    pl: '<h3>Dziękujemy za rejestrację!</h3><p stype="font-size: 18px">Wkrótce powinieneś/powinnaś otrzymać e-mail z potwierdzeniem.</p>',
    cs: '<h3>Děkujeme za registraci!</h3><p stype="font-size: 18px">Brzy by ti měl přijít potvrzovací e-mail.</p>',
    default:
      '<h3>Thank you for your registration!<p stype="font-size: 18px">You should receive a confirmation email shortly.</p>',
  },
  pages: [
    {
      name: 'p_overview',
      elements: [
        {
          type: 'expression',
          name: 'i_date',
          title: {
            en: 'Date',
            de: 'Datum',
            fr: 'Date',
            pl: 'Data',
            cs: 'Datum',
          },
          description: {
            en: '{camp.startAtDate} until {camp.endAtDate}',
            de: '{camp.startAtDate} bis {camp.endAtDate}',
            fr: '{camp.startAtDate} au {camp.endAtDate}',
            pl: '{camp.startAtDate} do {camp.endAtDate}',
            cs: '{camp.startAtDate} až {camp.endAtDate}',
            default: '{camp.startAtDate} until {camp.endAtDate}  ',
          },
        },
        {
          type: 'expression',
          name: 'i_age',
          title: {
            en: 'Age',
            de: 'Alter',
            fr: 'Âge',
            pl: 'Wiek',
            cs: 'Věk',
            default: 'Age',
          },
          description: {
            en: '{camp.minAge} to {camp.maxAge}',
            de: '{camp.minAge} bis {camp.maxAge}',
            fr: '{camp.minAge} à {camp.maxAge}',
            pl: '{camp.minAge} do {camp.maxAge}',
            cs: '{camp.minAge} až {camp.maxAge}',
            default: '{camp.minAge} to {camp.maxAge}',
          },
        },
        {
          type: 'expression',
          name: 'i_location',
          title: {
            en: 'Location',
            de: 'Ort',
            fr: 'Lieu',
            pl: 'Miejsce',
            cs: 'Místo',
            default: 'Location',
          },
          description: '{camp.location}',
        },
        {
          type: 'expression',
          name: 'i_price',
          title: {
            en: 'Price',
            de: 'Preis',
            fr: 'Prix',
            pl: 'Cena',
            cs: 'Cena',
            default: 'Price',
          },
          description: '{camp.price} €',
          currency: 'EUR',
        },
        {
          type: 'role',
          name: 'role',
          title: {
            en: 'Role',
            fr: 'Rôle',
            de: 'Rolle',
            pl: 'Rola',
            cs: 'Role',
            default: 'Role',
          },
          defaultValue: 'participant',
          isRequired: true,
          campDataType: 'role',
        },
      ],
      title: {
        en: 'Information',
        de: 'Informationen',
        fr: 'Informations',
        pl: 'Informacje',
        cs: 'Informace',
        default: 'Information',
      },
    },
    {
      name: 'p_general_information',
      elements: [
        {
          type: 'text',
          name: 'first_name',
          title: {
            en: 'First Name',
            de: 'Vorname',
            fr: 'Prénom',
            pl: 'Imię',
            cs: 'Jméno',
            default: 'First Name',
          },
          isRequired: true,
          campDataType: 'first_name',
          autocomplete: 'given-name',
        },
        {
          type: 'text',
          name: 'last_name',
          startWithNewLine: false,
          title: {
            en: 'Last Name',
            de: 'Nachname',
            fr: 'Nom de Famille',
            pl: 'Nazwisko',
            cs: 'Příjmení',
            default: 'Last Name',
          },
          isRequired: true,
          campDataType: 'last_name',
          autocomplete: 'family-name',
        },
        {
          type: 'dropdown',
          name: 'gender',
          title: {
            en: 'Gender',
            de: 'Geschlecht',
            fr: 'Sexe',
            pl: 'Płeć',
            cs: 'Pohlaví',
            default: 'Gender',
          },
          isRequired: true,
          choices: [
            {
              value: 'm',
              text: {
                en: 'male',
                de: 'männlich',
                fr: 'masculin',
                pl: 'mężczyzna',
                cs: 'muž',
                default: 'male',
              },
            },
            {
              value: 'f',
              text: {
                en: 'female',
                de: 'weiblich',
                fr: 'féminin',
                pl: 'kobieta',
                cs: 'žena',
                default: 'female',
              },
            },
            {
              value: 'd',
              text: {
                en: 'diverse',
                de: 'divers',
                fr: 'divers',
                pl: 'inne',
                cs: 'jiné',
                default: 'divers',
              },
            },
          ],
          autocomplete: 'sex',
        },
        {
          type: 'date_of_birth',
          name: 'date_of_birth',
          visibleIf: "{role} = 'participant'",
          title: {
            en: 'Date of Birth',
            de: 'Geburtsdatum',
            fr: 'Date de naissance',
            pl: 'Data urodzenia',
            cs: 'Datum narození',
            default: 'Date of Birth',
          },
          isRequired: true,
          campDataType: 'date_of_birth',
        },
        {
          type: 'text',
          name: 'counselor_date_of_birth',
          visibleIf: "{role} <> 'participant'",
          title: {
            en: 'Date of Birth',
            de: 'Geburtsdatum',
            fr: 'Date de naissance',
            pl: 'Data urodzenia',
            cs: 'Datum narození',
            default: 'Date of Birth',
          },
          valueName: 'date_of_birth',
          isRequired: true,
          campDataType: 'date_of_birth',
          inputType: 'date',
          autocomplete: 'bday',
          placeholder: {
            en: 'dd.mm.yyyy',
            de: 'tt.mm.jjjj',
            fr: 'jj.mm.aaaa',
            pl: 'dd.mm.rrrr',
            cs: 'dd.mm.rrrr',
            default: 'dd.mm.yyyy',
          },
        },
      ],
      title: {
        en: 'General Information',
        de: 'Allgemeine Informationen',
        fr: 'Informations générales',
        pl: 'Informacje ogólne',
        cs: 'Obecné informace',
        default: 'General Information',
      },
    },
    {
      name: 'p_contact',
      elements: [
        {
          type: 'address',
          name: 'address',
          title: {
            en: 'Address',
            de: 'Adresse',
            fr: 'Adresse',
            pl: 'Adres',
            cs: 'Adresa',
            default: 'Address',
          },
          isRequired: true,
          campDataType: 'address',
        },
        {
          type: 'text',
          name: 'email',
          title: {
            en: 'E-Mail',
            de: 'E-Mail',
            fr: 'E-Mail',
            pl: 'E-mail',
            cs: 'E-mail',
            default: 'E-Mail',
          },
          isRequired: true,
          campDataType: 'email',
          inputType: 'email',
          autocomplete: 'email',
        },
        {
          type: 'text',
          name: 'phone_number',
          title: {
            en: 'Phone Number',
            de: 'Handynummer',
            fr: 'Numéro de portable',
            pl: 'Numer telefonu komórkowego',
            cs: 'Číslo mobilního telefonu',
            default: 'Phone Number',
          },
          description: {
            en: 'If you do not have your own telephone number, you can leave this field blank',
            de: 'Wenn du keine eigene Telefonnummer hast, kannst du dieses Feld leer lassen',
            fr: "Si tu n'as pas de numéro de téléphone personnel, tu peux laisser ce champ vide",
            pl: 'Jeśli nie masz własnego numeru telefonu, możesz pozostawić to pole puste',
            cs: 'Pokud nemáš vlastní telefonní číslo, můžeš toto pole nechat prázdné',
            default:
              'If you do not have your own telephone number, you can leave this field blank',
          },
          requiredIf: '{isadult}',
          inputType: 'tel',
          autocomplete: 'tel',
        },
        {
          type: 'boolean',
          name: 'waiting_list',
          visible: false,
          visibleIf: '{waitingList} = true',
          title: {
            en: 'Waiting list',
            de: 'Warteliste',
            fr: "Liste d'attente",
            pl: 'Lista oczekujących',
            cs: 'Čekací listina',
            default: 'Waiting list',
          },
          description: {
            en: 'Unfortunately, all places for participants from this country are already taken. However, you can put your name on the waiting list. We will inform you as soon as a place becomes available.',
            de: 'Leider sind bereits alle Plätze für Teilnehmer aus diesem Land belegt. Du kannst dich aber auf die Warteliste setzten. Wir informieren dich dann sobald ein Platz frei wird.',
            fr: "Malheureusement, toutes les places pour les participants de ce pays sont déjà prises. Tu peux toutefois t'inscrire sur la liste d'attente. Nous t'informerons dès qu'une place se libérera.",
            pl: 'Niestety wszystkie miejsca dla uczestników z tego kraju są już zajęte. Możesz jednak zapisać się na listę oczekujących. Poinformujemy Cię, gdy tylko zwolni się miejsce.',
            cs: 'Bohužel jsou všechna místa pro účastníky z této země již obsazena. Můžeš se ale zapsat na čekací listinu. Dáme ti vědět, jakmile se uvolní místo.',
            default:
              'Unfortunately, all places for participants from this country are already taken. However, you can put your name on the waiting list. We will inform you as soon as a place becomes available.',
          },
          correctAnswer: true,
          isRequired: true,
          validators: [
            {
              type: 'expression',
              text: {
                en: 'Please confirm that you wish to be on the waiting list',
                de: 'Bitte bestätige, dass du auf die Warteliste möchtest',
                fr: "Confirme que tu souhaites être sur la liste d'attente",
                pl: 'Potwierdź, że chcesz znaleźć się na liście oczekujących',
                cs: 'Potvrď, že chceš být na čekací listině',
                default:
                  "Confirme que tu souhaites être sur la liste d'attente",
              },
              expression: '{waiting_list} = true',
            },
          ],
        },
      ],
      title: {
        en: 'Contact Information',
        de: 'Kontaktinformationen',
        fr: 'Coordonnées',
        pl: 'Dane kontaktowe',
        cs: 'Kontaktní údaje',
        default: 'Contact Information',
      },
    },
    {
      name: 'p_guardian',
      elements: [
        {
          type: 'text',
          name: 'guardian_first_name',
          title: {
            en: 'First Name',
            de: 'Vorname',
            fr: 'Prénom',
            pl: 'Imię',
            cs: 'Jméno',
            default: 'First Name',
          },
          isRequired: true,
          autocomplete: 'given-name',
        },
        {
          type: 'text',
          name: 'guardian_last_name',
          startWithNewLine: false,
          title: {
            en: 'Last Name',
            de: 'Nachname',
            fr: 'Nom',
            pl: 'Nazwisko',
            cs: 'Příjmení',
            default: 'Last Name',
          },
          isRequired: true,
          autocomplete: 'family-name',
        },
        {
          type: 'text',
          name: 'guardian_email',
          title: {
            en: 'E-Mail',
            de: 'E-Mail',
            fr: 'E-Mail',
            pl: 'E-mail',
            cs: 'E-mail',
            default: 'E-Mail',
          },
          isRequired: true,
          campDataType: 'email',
          inputType: 'email',
          autocomplete: 'email',
        },
      ],
      visibleIf: '{isminor}',
      title: {
        en: 'Information about legal guardians',
        de: 'Informationen über Sorgeberechtigten',
        fr: 'Informations sur les tuteurs légaux',
        pl: 'Informacje o opiekunach prawnych',
        cs: 'Informace o zákonných zástupcích',
        default: 'Information about legal guardians',
      },
    },
    {
      name: 'p_emergency_contact',
      elements: [
        {
          type: 'paneldynamic',
          name: 'guardian_emergency_contacts',
          title: {
            en: 'Emergency contacts',
            de: 'Erreichbarkeit in Notfällen',
            fr: "Contacts en cas d'urgence",
            pl: 'Kontakty awaryjne',
            cs: 'Kontakty pro nouzi',
            default: 'Emergency contacts',
          },
          description: {
            en: 'Who can we contact in an emergency? Several contacts can be specified.',
            de: 'Wen können wir in Notfällen kontaktieren? Es können mehrere Kontakte angegeben werden.',
            fr: "Qui peut-on contacter en cas d'urgence ? Il est possible d'indiquer plusieurs contacts.",
            pl: 'Kogo możemy skontaktować w nagłym wypadku? Można podać kilka kontaktów.',
            cs: 'Koho můžeme kontaktovat v případě nouze? Lze uvést více kontaktů.',
            default:
              'Who can we contact in an emergency? Several contacts can be specified.',
          },
          valueName: 'emergency_contacts',
          isRequired: true,
          requiredIf: '{isminor} = true',
          templateElements: [
            {
              type: 'text',
              name: 'emergency_contact_description',
              title: {
                en: 'Description',
                de: 'Beschreibung',
                fr: 'Description',
                pl: 'Opis',
                cs: 'Popis',
                default: 'Description',
              },
              description: {
                en: 'e.g. mother, father, landline, ...',
                de: 'z.B. Mutter, Vater, Festnetz, ...',
                fr: 'p.ex. mère, père, téléphone fixe, ...',
                pl: 'np. mama, tata, telefon stacjonarny, ...',
                cs: 'např. matka, otec, pevná linka, ...',
                default: 'e.g. mother, father, landline, ...',
              },
              valueName: 'description',
              isRequired: true,
            },
            {
              type: 'text',
              name: 'guardian_phone_number',
              title: {
                en: 'Phone Number',
                de: 'Telefonnummer',
                fr: 'Numéro de Téléphone',
                pl: 'Numer telefonu',
                cs: 'Telefonní číslo',
                default: 'Phone Number',
              },
              description: {
                en: 'with country code',
                de: 'mit Ländervorwahl',
                fr: "avec l'indicatif du pays",
                pl: 'z kodem kraju',
                cs: 's předvolbou země',
                default: 'with country code',
              },
              valueName: 'phone_number',
              isRequired: true,
              inputType: 'tel',
              autocomplete: 'tel',
            },
          ],
          noEntriesText: {
            en: 'There are no contacts yet. Click on the button below to add a new contact.',
            de: 'Es gibt noch keine Kontakte. Klicke auf die Schaltfläche unten, um einen neuen Kontakt hinzuzufügen.',
            fr: "Il n'y a pas encore de contacts. Clique sur le bouton ci-dessous pour ajouter un nouveau contact.",
            pl: 'Nie ma jeszcze żadnych kontaktów. Kliknij przycisk poniżej, aby dodać nowy kontakt.',
            cs: 'Zatím nejsou uvedeny žádné kontakty. Klikni na tlačítko níže a přidej nový kontakt.',
            default:
              'There are no contacts yet. Click on the button below to add a new contact.',
          },
          panelCount: 1,
          minPanelCount: 1,
          maxPanelCount: 3,
          panelAddText: {
            en: 'Add contact',
            de: 'Kontakt hinzufügen',
            fr: 'Ajouter un contact',
            pl: 'Dodaj kontakt',
            cs: 'Přidat kontakt',
            default: 'Add contact',
          },
        },
      ],
      title: {
        en: 'Emergency contacts',
        de: 'Notfallkontakte',
        fr: "Contacts en cas d'urgence",
        pl: 'Kontakty awaryjne',
        cs: 'Kontakty pro nouzi',
        default: 'Emergency contacts',
      },
    },
    {
      name: 'p_permissions',
      elements: [
        {
          type: 'boolean',
          name: 'permission_swim',
          title: {
            en: '{first_name} can and may swim freely',
            de: '{first_name} kann und darf frei schwimmen',
            fr: '{first_name} peut et sait nager librement',
            pl: '{first_name} może i potrafi swobodnie pływać',
            cs: '{first_name} může a umí volně plavat',
            default: '{first_name} can and may swim freely',
          },
          isRequired: true,
          labelTrue: {
            en: 'Yes',
            de: 'Ja',
            fr: 'Oui',
            pl: 'Tak',
            cs: 'Ano',
            default: 'Yes',
          },
          labelFalse: {
            en: 'No',
            de: 'Nein',
            fr: 'Non',
            pl: 'Nie',
            cs: 'Ne',
            default: 'No',
          },
        },
        {
          type: 'boolean',
          name: 'permission_written_consent',
          title: {
            en: '{first_name} may participate in leisure activities for which the organizer requires a written declaration of consent from the legal guardian',
            de: '{first_name} darf an Freizeitaktivitäten teilnehmen, bei denen der Veranstalter eine schriftliche Einverständniserklärung der Sorgeberechtigten benötigt',
            fr: "{first_name} peut participer à des activités de loisirs pour lesquelles l'organisateur a besoin d'une autorisation écrite du titulaire de l'autorité parentale",
            pl: '{first_name} może uczestniczyć w zajęciach rekreacyjnych, na które organizator wymaga pisemnej zgody opiekuna prawnego',
            cs: '{first_name} se může účastnit volnočasových aktivit, k nimž pořadatel vyžaduje písemný souhlas zákonného zástupce',
            default:
              '{first_name} may participate in leisure activities for which the organizer requires a written declaration of consent from the legal guardian',
          },
          description: {
            en: 'e.g. climbing park, go-karting or similar',
            de: 'z.B. Kletterpark, Go-Kart oder ähnliches',
            fr: "p. ex. parc d'escalade, karting ou autre",
            pl: 'np. park linowy, gokarty itp.',
            cs: 'např. lanové centrum, motokáry apod.',
            default: 'e.g. climbing park, go-karting or similar',
          },
          isRequired: true,
          labelTrue: {
            en: 'Yes',
            de: 'Ja',
            fr: 'Oui',
            pl: 'Tak',
            cs: 'Ano',
            default: 'Yes',
          },
          labelFalse: {
            en: 'No',
            de: 'Nein',
            fr: 'Non',
            pl: 'Nie',
            cs: 'Ne',
            default: 'No',
          },
        },
        {
          type: 'dropdown',
          name: 'permission_leave',
          title: {
            en: "{first_name} may leave the camp or the camp management's supervision area in consultation with the camp management",
            de: '{first_name} darf in Absprache mit der Lagerleitung das Camp bzw. den Aufsichtsbereich der Lagerleitung verlassen',
            fr: '{first_name} est autorisé à quitter le camp ou la zone de surveillance de la direction du camp en accord avec celle-ci',
            pl: '{first_name} może, po uzgodnieniu z kadrą, opuścić teren obozu lub strefę nadzoru kadry',
            cs: '{first_name} může po dohodě s vedením tábora opustit tábor nebo oblast jeho dozoru',
            default:
              "{first_name} may leave the camp or the camp management's supervision area in consultation with the camp management",
          },
          isRequired: true,
          choices: [
            {
              value: 2,
              text: {
                en: 'Alone',
                de: 'Alleine',
                fr: 'Seul',
                pl: 'Samodzielnie',
                cs: 'Sám/Sama',
                default: 'Alone',
              },
            },
            {
              value: 1,
              text: {
                en: 'In groups of at least 3 people',
                de: 'In Gruppen von mindestens 3 Personen',
                fr: "En groupes d'au moins 3 personnes",
                pl: 'W grupach co najmniej 3 osób',
                cs: 'Ve skupinách alespoň 3 osob',
                default: 'In groups of at least 3 people',
              },
            },
            {
              value: 0,
              text: {
                en: 'No',
                de: 'Nein',
                fr: 'Non',
                pl: 'Nie',
                cs: 'Ne',
                default: 'No',
              },
            },
          ],
          placeholder: {
            en: 'Selection...',
            de: 'Auswahl...',
            fr: 'Sélection...',
            pl: 'Wybór...',
            cs: 'Výběr...',
            default: 'Selection...',
          },
        },
      ],
      visibleIf: '{isminor}',
      title: {
        en: 'Permissions',
        de: 'Berechtigungen',
        fr: 'Autorisations',
        pl: 'Uprawnienia',
        cs: 'Oprávnění',
        default: 'Permissions',
      },
    },
    {
      name: 'p_additional_information',
      elements: [
        {
          type: 'text',
          name: 'medical_restrictions',
          title: {
            en: 'Medical Restrictions',
            de: 'Medizinische Einschränkungen',
            fr: 'Restrictions médicales',
            pl: 'Ograniczenia medyczne',
            cs: 'Zdravotní omezení',
            default: 'Medical Restrictions',
          },
          description: {
            en: 'Illnesses, allergies or other restrictions that could be relevant for the camp',
            de: 'Krankheiten, Allergien oder sonstige Einschränkungen, die für das Camp relevant sein könnten',
            fr: 'Maladies, allergies ou autres restrictions qui pourraient être pertinentes pour le camp',
            pl: 'Choroby, alergie lub inne ograniczenia, które mogą być istotne na obozie',
            cs: 'Nemoci, alergie či jiná omezení, která mohou být pro tábor relevantní',
            default:
              'Illnesses, allergies or other restrictions that could be relevant for the camp',
          },
        },
        {
          type: 'text',
          name: 'food_intolerance',
          title: {
            en: 'Special nutrition',
            de: 'Besondere Ernährung',
            fr: 'Alimentation spéciale',
            pl: 'Specjalna dieta',
            cs: 'Speciální strava',
            default: 'Special nutrition',
          },
          description: {
            en: 'Vegetarian, vegan, etc.',
            de: 'Vegetarisch, Vegan o.Ä.',
            fr: 'Végétarien, végétalien, etc.',
            pl: 'Wegetariańska, wegańska itp.',
            cs: 'Vegetariánská, veganská apod.',
            default: 'Vegetarian, vegan, etc.',
          },
        },
        {
          type: 'comment',
          name: 'additional_information',
          title: {
            en: 'Additional information',
            de: 'Sonstige Informationen',
            fr: 'Autres informations',
            pl: 'Dodatkowe informacje',
            cs: 'Další informace',
            default: 'Additional information',
          },
          description: {
            en: 'You can give us more information here.',
            de: 'Hier kannst du uns noch weitere Informationen mitteilen.',
            fr: "Ici, tu peux nous communiquer d'autres informations.",
            pl: 'Tutaj możesz przekazać nam dodatkowe informacje.',
            cs: 'Zde nám můžeš sdělit další informace.',
            default: 'You can give us more information here.',
          },
        },
      ],
      title: {
        en: 'Additional Information',
        de: 'Weitere Informationen',
        fr: 'Informations supplémentaires',
        pl: 'Dodatkowe informacje',
        cs: 'Další informace',
        default: 'Additional Information',
      },
    },
    {
      name: 'p_consent',
      elements: [
        {
          type: 'boolean',
          name: 'consent_rules',
          title: {
            en: `I have read the [camp rules](${host}/) and agree to them.`,
            de: `Ich habe die [Campregeln](${host}/) gelesen und bin damit einverstanden.`,
            fr: `J'ai lu et j'accepte le [règlement](${host}/) de la colonie de vacances.`,
            pl: `Przeczytałem/łam [regulamin obozu](${host}/) i akceptuję go.`,
            cs: `Přečetl/a jsem si [táborová pravidla](${host}/) a souhlasím s nimi.`,
            default: `I have read the [camp rules](${host}/) and agree to them.`,
          },
          correctAnswer: true,
          isRequired: true,
          requiredErrorText: {
            en: 'You must agree to the camp rules in order to participate in the camp',
            de: 'Du musst den Campregeln zustimmen, um am Camp teilnehmen zu können',
            fr: 'Tu dois accepter le règlement du camp pour pouvoir y participer.',
            pl: 'Aby wziąć udział w obozie, musisz zaakceptować regulamin obozu',
            cs: 'Pro účast na táboře musíš souhlasit s táborovými pravidly',
            default:
              'You must agree to the camp rules in order to participate in the camp',
          },
          validators: [
            {
              type: 'expression',
              text: {
                en: 'You must agree to the camp rules in order to participate in the camp',
                de: 'Du musst den Campregeln zustimmen, um am Camp teilnehmen zu können',
                fr: 'Tu dois accepter le règlement du camp pour pouvoir y participer.',
                pl: 'Aby wziąć udział w obozie, musisz zaakceptować regulamin obozu',
                cs: 'Pro účast na táboře musíš souhlasit s táborovými pravidly',
                default:
                  'You must agree to the camp rules in order to participate in the camp',
              },
              expression: '{consent_rules} = true',
            },
          ],
        },
        {
          type: 'boolean',
          name: 'consent_general_terms_and_conditions',
          title: {
            en: `I have read the [General Terms and Conditions](${host}/) and agree to them.`,
            de: `Ich habe die [allgemeinen Geschäftsbedingungen](${host}/) gelesen und stimme diesen zu.`,
            fr: `J'ai lu et j'accepte les [conditions générales](${host}/).`,
            pl: `Przeczytałem/łam [regulamin / warunki uczestnictwa](${host}/) i je akceptuję.`,
            cs: `Přečetl/a jsem si [obchodní podmínky](${host}/) a souhlasím s nimi.`,
            default: `I have read the [General Terms and Conditions](${host}/) and agree to them.`,
          },
          correctAnswer: true,
          isRequired: true,
          requiredErrorText: {
            en: 'You must agree to our terms and conditions in order to participate!',
            de: 'Du musst unseren AGB zustimmen, um teilnehmen zu können!',
            fr: 'Tu dois accepter nos conditions générales pour pouvoir participer !',
            pl: 'Aby wziąć udział, musisz zaakceptować nasze warunki!',
            cs: 'Pro účast musíš souhlasit s našimi podmínkami!',
            default:
              'You must agree to our terms and conditions in order to participate!',
          },
          validators: [
            {
              type: 'expression',
              text: {
                en: 'You must agree to our terms and conditions in order to participate!',
                de: 'Du musst unseren AGB zustimmen, um teilnehmen zu können!',
                fr: 'Tu dois accepter nos conditions générales pour pouvoir participer !',
                pl: 'Aby wziąć udział, musisz zaakceptować nasze warunki!',
                cs: 'Pro účast musíš souhlasit s našimi podmínkami!',
                default:
                  'You must agree to our terms and conditions in order to participate!',
              },
              expression: '{consent_general_terms_and_conditions} = true',
            },
          ],
        },
        {
          type: 'boolean',
          name: 'consent_forward_list_participants',
          title: {
            en: 'I agree that my contact details (address, e-mail, telephone) may only be passed on to other camp participants in the form of a list of participants for the purpose of carpooling.',
            de: 'Ich stimme zu, dass meine Kontaktdaten (Anschrift, E-Mail, Telefon) in Form einer Teilnehmerliste zur Bildung von Fahrgemeinschaften ausschließlich an andere Teilnehmer des Camps weitergeleitet werden dürfen.',
            fr: "J'accepte que mes coordonnées (adresse, e-mail, téléphone) soient transmises exclusivement aux autres participants du camp de vacances sous la forme d'une liste de participants pour le covoiturage.",
            pl: 'Wyrażam zgodę na przekazanie moich danych kontaktowych (adres, e-mail, telefon) innym uczestnikom obozu w formie listy uczestników w celu organizacji wspólnych przejazdów.',
            cs: 'Souhlasím s tím, aby byly mé kontaktní údaje (adresa, e-mail, telefon) předány ostatním účastníkům tábora ve formě seznamu účastníků za účelem spolujízdy.',
            default:
              'I agree that my contact details (address, e-mail, telephone) may only be passed on to other camp participants in the form of a list of participants for the purpose of carpooling.',
          },
        },
        {
          type: 'boolean',
          name: 'consent_privacy',
          title: {
            en: 'I agree that photographs of the participant, {first_name} {last_name}, may be taken and made available to the organizer for the purpose of media coverage and advertising.',
            de: 'Ich stimme zu, dass von dem Teilnehmenden, {first_name} {last_name} Aufnahmen erstellt werden dürfen und dem Veranstalter zum Zwecke der Berichterstattung in Medien und für Werbezwecke zur Verfügung gestellt werden.',
            fr: "J'accepte que des photos du participant, {first_name} {last_name}, soient prises et mises à la disposition de l'organisateur à des fins de reportage dans les médias et de publicité.",
            pl: 'Wyrażam zgodę na wykonywanie zdjęć uczestnika {first_name} {last_name} oraz ich udostępnianie organizatorowi w celach relacji medialnych i promocyjnych.',
            cs: 'Souhlasím s pořízením fotografií účastníka {first_name} {last_name} a jejich poskytnutím pořadateli pro mediální prezentaci a propagační účely.',
            default:
              'I agree that photographs of the participant, {first_name} {last_name}, may be taken and made available to the organizer for the purpose of media coverage and advertising.',
          },
          description: {
            en: 'Consent is voluntary and can be revoked at any time without giving reasons.',
            de: 'Die Zustimmung ist Freiwillig und kann jederzeit ohne Angabe von Gründen widerrufen werden.',
            fr: 'Le consentement est volontaire et peut être retiré à tout moment sans justification.',
            pl: 'Zgoda jest dobrowolna i może zostać w każdej chwili odwołana bez podania przyczyny.',
            cs: 'Souhlas je dobrovolný a lze jej kdykoli bez udání důvodu odvolat.',
            default:
              'Consent is voluntary and can be revoked at any time without giving reasons.',
          },
        },
        {
          type: 'boolean',
          name: 'confirmation_guardian',
          visibleIf: '{isminor} = true',
          title: {
            en: 'I confirm that I am the legal guardian of {first_name} {last_name}.',
            de: 'Ich bestätige, dass ich Sorgeberechtige:r von {first_name} {last_name} bin.',
            fr: "Je confirme que je suis l'autorité parentale de {first_name} {last_name}.",
            pl: 'Potwierdzam, że jestem opiekunem prawnym {first_name} {last_name}.',
            cs: 'Potvrzuji, že jsem zákonným zástupcem {first_name} {last_name}.',
            default:
              'I confirm that I am the legal guardian of {first_name} {last_name}.',
          },
          correctAnswer: false,
          isRequired: true,
          validators: [
            {
              type: 'expression',
              text: {
                en: 'You must be a legal guardian',
                de: 'Sie müssen Sorgeberechtigte:r sein',
                fr: "Vous devez être titulaire de l'autorité parentale",
                pl: 'Musisz być opiekunem prawnym',
                cs: 'Musíš být zákonným zástupcem',
                default: 'You must be a legal guardian',
              },
              expression: '{confirmation_guardian} = true',
            },
          ],
        },
      ],
      title: {
        en: 'Consents',
        fr: 'Approbations',
        de: 'Zustimmung',
        pl: 'Zgody',
        cs: 'Souhlasy',
        default: 'Consents',
      },
    },
  ],
  calculatedValues: [
    {
      name: 'isadult',
      expression: 'isAdult({date_of_birth}, {camp.startAt})',
    },
    {
      name: 'isminor',
      expression: 'isMinor({date_of_birth}, {camp.startAt})',
    },
    {
      name: 'waitingList',
      expression: 'isWaitingList({camp.freePlaces}, {country})',
    },
  ],
  showQuestionNumbers: 'off',
  showProgressBar: 'bottom',
  completeText: {
    en: 'Register for a fee',
    de: 'Kostenpflichtig Anmelden',
    fr: 'Inscription payante',
    pl: 'Zarejestruj się (płatne)',
    cs: 'Zaregistrovat se (placeně)',
    default: 'Register for a fee',
  },
  widthMode: 'responsive',
};
