export default [
  {
    title: {
      en: 'Overview',
      de: 'Übersicht',
      fr: 'Aperçu',
      cs: 'Přehled',
      pl: 'Przegląd',
    },
    order: 0,
    columns: [
      {
        name: 'first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          cs: 'Jméno',
          pl: 'Imię',
        },
        field: 'data.first_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          cs: 'Příjmení',
          pl: 'Nazwisko',
        },
        field: 'data.last_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'age',
        label: {
          en: 'Age',
          de: 'Alter',
          fr: 'Âge',
          cs: 'Věk',
          pl: 'Wiek',
        },
        field: 'data.date_of_birth',
        renderAs: 'age',
        align: 'center',
        shrink: true,
        sortable: true,
      },
      {
        name: 'gender',
        label: {
          en: 'Gender',
          de: 'Geschlecht',
          fr: 'Sexe',
          cs: 'Pohlaví',
          pl: 'Płeć',
        },
        field: 'data.gender',
        renderAs: 'gender',
        align: 'center',
        shrink: true,
        sortable: true,
      },
      {
        name: 'country',
        label: {
          en: 'Country',
          de: 'Land',
          fr: 'Pays',
          cs: 'Země',
          pl: 'Kraj',
        },
        field: 'data.address.country',
        renderAs: 'country_flag',
        align: 'center',
        shrink: true,
        sortable: true,
      },
      {
        name: 'status',
        label: {
          en: 'Status',
          de: 'Status',
          fr: 'Statut',
          cs: 'Stav',
          pl: 'Status',
        },
        field: 'status',
        renderAs: 'status',
        align: 'center',
        sortable: true,
      },
      {
        name: 'created_at',
        label: {
          en: 'Registration time',
          de: 'Anmeldezeitpunkt',
          fr: "Moment de l'inscription",
          cs: 'Čas registrace',
          pl: 'Czas rejestracji',
        },
        field: 'createdAt',
        renderAs: 'time_ago',
        align: 'left',
        sortable: true,
      },
      {
        name: 'additional_information',
        label: {
          en: 'Additional information',
          de: 'Weitere Informationen',
          fr: "Plus d'informations",
          cs: 'Další informace',
          pl: 'Dodatkowe informacje',
        },
        field: 'data.additional_information',
        renderAs: 'text',
        align: 'left',
        shrink: true,
      },
    ],
    indexed: true,
    actions: true,
    sortBy: 'created_at',
    filterStatus: undefined,
    sortDirection: 'desc',
    filterRoles: ['counselor'],
  },
  {
    title: {
      en: 'List of participants',
      de: 'Teilnehmerliste',
      fr: 'Liste des participants',
      cs: 'Seznam účastníků',
      pl: 'Lista uczestników',
    },
    order: 1,
    columns: [
      {
        name: 'first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          cs: 'Jméno',
          pl: 'Imię',
        },
        field: 'data.first_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          cs: 'Příjmení',
          pl: 'Nazwisko',
        },
        field: 'data.last_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'phone_number',
        label: {
          en: 'Phone number',
          de: 'Telefonnummer',
          fr: 'Téléphone',
          cs: 'Telefonní číslo',
          pl: 'Numer telefonu',
        },
        field: 'data.phone_number',
        renderAs: 'phone_number',
        align: 'left',
      },
      {
        name: 'age',
        label: {
          en: 'Age',
          de: 'Alter',
          fr: 'Âge',
          cs: 'Věk',
          pl: 'Wiek',
        },
        field: 'data.date_of_birth',
        renderAs: 'age',
        align: 'center',
      },
      {
        name: 'permission_leave',
        label: {
          en: 'Leave',
          de: 'Verlassen',
          fr: 'Sortir',
          cs: 'Opustit',
          pl: 'Opuścić',
        },
        field: 'data.permission_leave',
        renderAs: 'permission_leave',
        align: 'center',
        shrink: true,
        headerVertical: true,
      },
      {
        name: 'permission_swim',
        label: {
          en: 'Swim',
          de: 'Schwimmen',
          fr: 'Nager',
          cs: 'Plavat',
          pl: 'Pływać',
        },
        field: 'data.permission_swim',
        renderAs: 'icon',
        align: 'center',
        renderOptions: {
          name: 'pool',
          color: 'negative',
        },
        headerVertical: true,
        shrink: true,
        showIf: '$data.permission_swim == false',
      },
      {
        name: 'privacy',
        label: {
          en: 'Photos',
          de: 'Fotos',
          fr: 'Photos',
          cs: 'Fotky',
          pl: 'Zdjęcia',
        },
        field: 'data.consent_privacy',
        renderAs: 'icon',
        align: 'center',
        headerVertical: true,
        shrink: true,
        showIf: '$data.consent_privacy != true',
        renderOptions: {
          name: 'no_photography',
          color: 'negative',
        },
      },
      {
        name: 'room',
        label: {
          en: 'Room',
          de: 'Zimmer',
          fr: 'Chambre',
          cs: 'Pokoj',
          pl: 'Pokój',
        },
        field: 'room',
        renderAs: 'translated_value',
        align: 'left',
      },
    ],
    indexed: true,
    sortBy: 'first_name',
    filterStatus: ['ACCEPTED'],
    filterRoles: ['counselor'],
  },
  {
    title: {
      en: 'Counselors',
      de: 'Betreuer',
      fr: 'Conseillers',
      cs: 'Vedoucí',
      pl: 'Opiekunowie',
    },
    order: 2,
    columns: [
      {
        name: 'first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          cs: 'Jméno',
          pl: 'Imię',
        },
        field: 'data.first_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          cs: 'Příjmení',
          pl: 'Nazwisko',
        },
        field: 'data.last_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'age',
        label: {
          en: 'Age',
          de: 'Alter',
          fr: 'Âge',
          cs: 'Věk',
          pl: 'Wiek',
        },
        field: 'data.date_of_birth',
        renderAs: 'age',
        align: 'center',
        sortable: true,
      },
      {
        name: 'country',
        label: {
          en: 'Country',
          de: 'Land',
          fr: 'Pays',
          cs: 'Země',
          pl: 'Kraj',
        },
        field: 'data.address.country',
        renderAs: 'country_flag',
        align: 'center',
        sortable: true,
      },
      {
        name: 'privacy',
        label: {
          en: 'Pictures',
          de: 'Fotos',
          fr: 'Photos',
          cs: 'Fotky',
          pl: 'Zdjęcia',
        },
        field: 'data.consent_privacy',
        renderAs: 'icon',
        showIf: '$data.consent_privacy != true',
        renderOptions: {
          name: 'no_photography',
          color: 'negative',
        },
        align: 'center',
        headerVertical: true,
      },
      {
        name: 'role',
        label: {
          en: 'Role',
          de: 'Rolle',
          fr: 'Rôle',
          cs: 'Role',
          pl: 'Rola',
        },
        field: 'data.role',
        renderAs: 'default',
        align: 'left',
      },
    ],
    sortBy: 'first_name',
    indexed: true,
    filterRoles: ['participant'],
  },
  {
    title: {
      en: 'Emergency Contacts',
      de: 'Notfallkontakte',
      fr: "Contacts d'urgence",
      cs: 'Kontakty pro nouze',
      pl: 'Kontakty awaryjne',
    },
    order: 3,
    columns: [
      {
        name: 'first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          cs: 'Jméno',
          pl: 'Imię',
        },
        field: 'data.first_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          cs: 'Příjmení',
          pl: 'Nazwisko',
        },
        field: 'data.last_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'age',
        label: {
          en: 'Age',
          de: 'Alter',
          fr: 'Âge',
          cs: 'Věk',
          pl: 'Wiek',
        },
        field: 'data.date_of_birth',
        renderAs: 'age',
        align: 'center',
      },
      {
        name: 'date_of_birth',
        label: {
          en: 'Date of birth',
          de: 'Geburtsdatum',
          fr: 'Date de naissance',
          cs: 'Datum narození',
          pl: 'Data urodzenia',
        },
        field: 'data.date_of_birth',
        renderAs: 'date',
        align: 'center',
        headerVertical: false,
        shrink: true,
      },
      {
        name: 'gender',
        label: {
          en: 'Gender',
          de: 'Geschlecht',
          fr: 'Sexe',
          cs: 'Pohlaví',
          pl: 'Płeć',
        },
        field: 'data.gender',
        renderAs: 'gender',
        align: 'center',
        shrink: true,
      },
      {
        name: 'contact_description',
        label: {
          en: 'Contact',
          de: 'Kontakt',
          fr: 'Contact',
          cs: 'Kontakt',
          pl: 'Kontakt',
        },
        field: 'data.emergency_contacts.*.description',
        renderAs: 'default',
        align: 'left',
        isArray: true,
      },
      {
        name: 'phone_number',
        label: {
          en: 'Phone number',
          fr: 'Numéro de téléphone',
          de: 'Telefonnummer',
          cs: 'Telefonní číslo',
          pl: 'Numer telefonu',
        },
        field: 'data.emergency_contacts.*.phone_number',
        renderAs: 'phone_number',
        isArray: true,
        align: 'left',
      },
    ],
    filterStatus: ['ACCEPTED'],
    sortBy: 'first_name',
    filterRoles: ['counselor'],
  },
  {
    title: {
      en: 'Legal guardian',
      de: 'Sorgeberechtigter',
      fr: 'Responsable légal',
      cs: 'Zákonný zástupce',
      pl: 'Opiekun prawny',
    },
    order: 4,
    columns: [
      {
        name: 'first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          cs: 'Jméno',
          pl: 'Imię',
        },
        field: 'data.first_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          cs: 'Příjmení',
          pl: 'Nazwisko',
        },
        field: 'data.last_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'guardian_first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          cs: 'Jméno',
          pl: 'Imię',
        },
        field: 'data.guardian_first_name',
        renderAs: 'name',
        align: 'left',
      },
      {
        name: 'guardian_last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          cs: 'Příjmení',
          pl: 'Nazwisko',
        },
        field: 'data.guardian_last_name',
        renderAs: 'name',
        align: 'left',
      },
      {
        name: 'guardian_email',
        label: {
          en: 'Email',
          de: 'E-Mail',
          fr: 'Email',
          cs: 'E-mail',
          pl: 'E-mail',
        },
        field: 'data.guardian_email',
        renderAs: 'email',
        align: 'left',
      },
    ],
    filterRoles: ['counselor'],
    filterStatus: ['ACCEPTED'],
    sortBy: 'first_name',
  },
  {
    title: {
      en: 'Contact details',
      de: 'Kontaktdaten',
      fr: 'Coordonnées',
      cs: 'Kontaktní údaje',
      pl: 'Dane kontaktowe',
    },
    order: 5,
    columns: [
      {
        name: 'first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          cs: 'Jméno',
          pl: 'Imię',
        },
        field: 'data.first_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          cs: 'Příjmení',
          pl: 'Nazwisko',
        },
        field: 'data.last_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'date_of_birth',
        label: {
          en: 'Age',
          de: 'Alter',
          fr: 'Âge',
          cs: 'Věk',
          pl: 'Wiek',
        },
        field: 'data.date_of_birth',
        renderAs: 'age',
        align: 'center',
      },
      {
        name: 'phone_number',
        label: {
          en: 'Phone number',
          de: 'Telefonnummer',
          fr: 'Téléphone',
          cs: 'Telefonní číslo',
          pl: 'Numer telefonu',
        },
        field: 'data.phone_number',
        renderAs: 'phone_number',
        align: 'left',
      },
      {
        name: 'email',
        label: {
          en: 'E-Mail',
          de: 'E-Mail',
          fr: 'E-Mail',
          cs: 'E-mail',
          pl: 'E-mail',
        },
        field: 'data.email',
        renderAs: 'email',
        align: 'left',
      },
      {
        name: 'address',
        label: {
          en: 'Address',
          de: 'Adresse',
          fr: 'Adresse',
          cs: 'Adresa',
          pl: 'Adres',
        },
        field: 'data.address',
        renderAs: 'address',
        align: 'left',
      },
      {
        name: 'forward',
        label: {
          en: 'Forward',
          de: 'Weiterleiten',
          fr: 'Transmettre',
          cs: 'Předat',
          pl: 'Przekazać',
        },
        field: 'data.consent_forward_list_participants',
        renderAs: 'default',
        sortable: true,
      },
    ],
    indexed: true,
    sortBy: 'first_name',
    filterStatus: ['ACCEPTED'],
    filterRoles: ['counselor'],
  },
  {
    title: {
      en: 'Additional information',
      de: 'Weitere Informationen',
      fr: "Plus d'informations",
      cs: 'Další informace',
      pl: 'Dodatkowe informacje',
    },
    order: 6,
    columns: [
      {
        name: 'first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          cs: 'Jméno',
          pl: 'Imię',
        },
        field: 'data.first_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          cs: 'Příjmení',
          pl: 'Nazwisko',
        },
        field: 'data.last_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'food',
        label: {
          en: 'Nutrition',
          de: 'Ernährung',
          fr: 'Alimentation',
          cs: 'Strava',
          pl: 'Dieta',
        },
        field: 'data.food_intolerance',
        renderAs: 'text',
        align: 'left',
      },
      {
        name: 'medical_restristrions',
        label: {
          en: 'Restrictions',
          de: 'Einschränkungen',
          fr: 'Restrictions',
          cs: 'Omezení',
          pl: 'Ograniczenia',
        },
        field: 'data.medical_restrictions',
        renderAs: 'text',
        align: 'left',
      },
      {
        name: 'additional_information',
        label: {
          en: 'Additional information',
          de: 'Weitere Informationen',
          fr: "Plus d'informations",
          cs: 'Další informace',
          pl: 'Dodatkowe informacje',
        },
        field: 'data.additional_information',
        renderAs: 'text',
        align: 'left',
      },
      {
        name: 'language_skills',
        label: {
          fr: 'Connaissances linguistiques',
          de: 'Sprachkenntnisse',
          en: 'Language skills',
          cs: 'Jazykové znalosti',
          pl: 'Umiejętności językowe',
        },
        field: 'data.language_skills',
        renderAs: 'language_skills',
        align: 'center',
        shrink: true,
      },
    ],
    indexed: true,
    filterStatus: ['ACCEPTED'],
    sortBy: 'first_name',
  },
  {
    title: {
      en: 'Waiting list',
      de: 'Warteliste',
      fr: "Liste d'attente",
      cs: 'Čekací listina',
      pl: 'Lista oczekujących',
    },
    order: 7,
    columns: [
      {
        name: 'first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          cs: 'Jméno',
          pl: 'Imię',
        },
        field: 'data.first_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          cs: 'Příjmení',
          pl: 'Nazwisko',
        },
        field: 'data.last_name',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'country',
        label: {
          en: 'Country',
          de: 'Land',
          fr: 'Pays',
          cs: 'Země',
          pl: 'Kraj',
        },
        field: 'data.address.country',
        renderAs: 'country_flag',
        align: 'center',
        shrink: true,
      },
      {
        name: 'date',
        label: {
          en: 'Timestamp',
          de: 'Zeitpunkt',
          fr: 'Moment',
          cs: 'Čas',
          pl: 'Czas',
        },
        field: 'createdAt',
        renderAs: 'time_ago',
        align: 'center',
        sortable: true,
      },
    ],
    filterStatus: ['WAITLISTED'],
    indexed: true,
    actions: true,
    sortBy: 'date',
  },
];
