export { default as campResource, detailedCampResource } from './camp.resource';
export { default as userResource } from './user.resource';
export { default as profileResource } from './profile.resource';
export { default as registrationResource } from './registration.resource';
export { default as tableTemplateResource } from './table-template.resource';
export { default as campManagerResource } from './manager.resource';
export { default as roomResource } from './room.resource';
export { default as bedResource } from './bed.rescource';
export { default as fileResource } from './file.rescource';
export { default as messageResource } from './message.resource';
