export default [
  {
    title: {
      en: 'Overview',
      de: 'Übersicht',
      fr: 'Aperçu',
      cs: 'Přehled',
      pl: 'Przegląd',
    },
    order: 0,
    columns: [
      {
        name: 'first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          cs: 'Jméno',
          pl: 'Imię',
        },
        field: 'data.first_name',
        source: 'form',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          cs: 'Příjmení',
          pl: 'Nazwisko',
        },
        field: 'data.last_name',
        source: 'form',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'age',
        label: {
          en: 'Age',
          de: 'Alter',
          fr: 'Âge',
          cs: 'Věk',
          pl: 'Wiek',
        },
        field: 'data.date_of_birth',
        source: 'form',
        renderAs: 'age',
        align: 'center',
        shrink: true,
        sortable: true,
      },
      {
        name: 'gender',
        label: {
          en: 'Gender',
          de: 'Geschlecht',
          fr: 'Sexe',
          cs: 'Pohlaví',
          pl: 'Płeć',
        },
        field: 'data.gender',
        source: 'form',
        renderAs: 'gender',
        align: 'center',
        shrink: true,
        sortable: true,
      },
      {
        name: 'email',
        label: {
          en: 'E-Mail',
          de: 'E-Mail',
          fr: 'E-Mail',
          cs: 'E-mail',
          pl: 'E-mail',
        },
        field: 'data.email',
        source: 'form',
        renderAs: 'email',
        align: 'left',
        sortable: false,
      },
      {
        name: 'status',
        label: {
          en: 'Status',
          de: 'Status',
          fr: 'Statut',
          cs: 'Stav',
          pl: 'Status',
        },
        field: 'status',
        source: 'meta',
        renderAs: 'status',
        align: 'center',
        sortable: true,
      },
      {
        name: 'created_at',
        label: {
          en: 'Registration time',
          de: 'Anmeldezeitpunkt',
          fr: "Moment de l'inscription",
          cs: 'Čas registrace',
          pl: 'Czas rejestracji',
        },
        field: 'createdAt',
        source: 'meta',
        renderAs: 'time_ago',
        align: 'left',
        sortable: true,
      },
    ],
    indexed: true,
    actions: true,
    sortBy: 'created_at',
    filterStatus: undefined,
    sortDirection: 'desc',
  },
  {
    title: {
      en: 'Waiting list',
      de: 'Warteliste',
      fr: "Liste d'attente",
      cs: 'Čekací listina',
      pl: 'Lista oczekujących',
    },
    order: 1,
    columns: [
      {
        name: 'first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          cs: 'Jméno',
          pl: 'Imię',
        },
        field: 'data.first_name',
        source: 'form',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          cs: 'Příjmení',
          pl: 'Nazwisko',
        },
        field: 'data.last_name',
        source: 'form',
        renderAs: 'name',
        align: 'left',
        sortable: true,
      },
      {
        name: 'email',
        label: {
          en: 'E-Mail',
          de: 'E-Mail',
          fr: 'E-Mail',
          cs: 'E-mail',
          pl: 'E-mail',
        },
        field: 'data.email',
        source: 'form',
        renderAs: 'email',
        align: 'left',
      },
      {
        name: 'date',
        label: {
          en: 'Timestamp',
          de: 'Zeitpunkt',
          fr: 'Moment',
          cs: 'Čas',
          pl: 'Czas',
        },
        field: 'createdAt',
        source: 'meta',
        renderAs: 'time_ago',
        align: 'center',
        sortable: true,
      },
    ],
    filterStatus: ['WAITLISTED'],
    indexed: true,
    actions: true,
    sortBy: 'date',
  },
];
