export default [
  {
    title: {
      en: 'Overview',
      de: 'Übersicht',
      fr: 'Aperçu',
      pl: 'Przegląd',
      cs: 'Přehled',
    },
    columns: [
      {
        name: 'first_name',
        field: 'data.first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          pl: 'Imię',
          cs: 'Jméno',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'last_name',
        field: 'data.last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          pl: 'Nazwisko',
          cs: 'Příjmení',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'role',
        field: 'data.role',
        label: {
          en: 'Role',
          de: 'Rolle',
          fr: 'Rôle',
          pl: 'Rola',
          cs: 'Role',
        },
        align: 'center',
        renderAs: 'default',
        sortable: true,
        shrink: true,
      },
      {
        name: 'age',
        field: 'data.date_of_birth',
        label: {
          en: 'Age',
          de: 'Alter',
          fr: 'Âge',
          pl: 'Wiek',
          cs: 'Věk',
        },
        align: 'center',
        renderAs: 'age',
        sortable: true,
        renderOptions: {
          showBirthday: true,
        },
        shrink: true,
      },
      {
        name: 'gender',
        field: 'data.gender',
        label: {
          en: 'Gender',
          de: 'Geschlecht',
          fr: 'Sexe',
          pl: 'Płeć',
          cs: 'Pohlaví',
        },
        align: 'center',
        renderAs: 'gender',
        sortable: true,
        shrink: true,
      },
      {
        name: 'country',
        field: 'data.address.country',
        label: {
          en: 'Country',
          de: 'Land',
          fr: 'Pays',
          pl: 'Kraj',
          cs: 'Země',
        },
        align: 'center',
        renderAs: 'country_flag',
        sortable: true,
        shrink: true,
      },
      {
        name: 'status',
        field: 'status',
        label: {
          en: 'Status',
          de: 'Status',
          fr: 'Statut',
          pl: 'Status',
          cs: 'Stav',
        },
        align: 'center',
        renderAs: 'status',
        sortable: true,
        shrink: true,
      },
      {
        name: 'waiting_list',
        field: 'data.waiting_list',
        label: {
          en: 'Waiting list',
          de: 'Warteliste',
          fr: 'Liste d’attente',
          pl: 'Lista oczekujących',
          cs: 'Čekací listina',
        },
        align: 'center',
        renderAs: 'icon',
        renderOptions: {
          name: 'hourglass_top',
          color: 'warning',
        },
        showIf: '$data.waiting_list == true',
        headerVertical: true,
        shrink: true,
      },
      {
        name: 'created_at',
        field: 'createdAt',
        label: {
          en: 'Registered',
          de: 'Angemeldet',
          fr: 'Inscrit',
          pl: 'Zarejestrowano',
          cs: 'Registrováno',
        },
        align: 'left',
        renderAs: 'time_ago',
        sortable: true,
      },
      {
        name: 'email',
        field: 'data.email',
        label: {
          en: 'E-mail',
          de: 'E-Mail',
          fr: 'E-mail',
          pl: 'E-mail',
          cs: 'E-mail',
        },
        align: 'left',
        renderAs: 'email',
      },
      {
        name: 'phone_number',
        field: 'data.phone_number',
        label: {
          en: 'Phone',
          de: 'Telefon',
          fr: 'Téléphone',
          pl: 'Telefon',
          cs: 'Telefon',
        },
        align: 'left',
        renderAs: 'phone_number',
      },
      {
        name: 'guardian_email',
        field: 'data.guardian_email',
        label: {
          en: 'Legal guardian e-mail',
          de: 'E-Mail Sorgeberechtigte',
          fr: 'E-mail responsable légal',
          pl: 'E-mail opiekuna prawnego',
          cs: 'E-mail zákonného zástupce',
        },
        align: 'left',
        renderAs: 'email',
      },
      {
        name: 'additional_information',
        field: 'data.additional_information',
        label: {
          en: 'Additional information',
          de: 'Weitere Informationen',
          fr: 'Informations supplémentaires',
          pl: 'Dodatkowe informacje',
          cs: 'Další informace',
        },
        align: 'left',
        renderAs: 'text',
        shrink: true,
      },
    ],
    order: 0,
    filterRoles: ['counselor', 'organizer'],
    indexed: true,
    actions: true,
    sortBy: 'created_at',
    sortDirection: 'desc',
    id: '01KVH6HQPTK7MKEXYVJZP76TMA',
  },
  {
    title: {
      en: 'Participants',
      de: 'Teilnehmende',
      fr: 'Participants',
      pl: 'Uczestnicy',
      cs: 'Účastníci',
    },
    columns: [
      {
        name: 'first_name',
        field: 'data.first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          pl: 'Imię',
          cs: 'Jméno',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'last_name',
        field: 'data.last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          pl: 'Nazwisko',
          cs: 'Příjmení',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'age',
        field: 'data.date_of_birth',
        label: {
          en: 'Age',
          de: 'Alter',
          fr: 'Âge',
          pl: 'Wiek',
          cs: 'Věk',
        },
        align: 'center',
        renderAs: 'age',
        sortable: true,
        shrink: true,
      },
      {
        name: 'gender',
        field: 'data.gender',
        label: {
          en: 'Gender',
          de: 'Geschlecht',
          fr: 'Sexe',
          pl: 'Płeć',
          cs: 'Pohlaví',
        },
        align: 'center',
        renderAs: 'gender',
        sortable: true,
        shrink: true,
      },
      {
        name: 'country',
        field: 'data.address.country',
        label: {
          en: 'Country',
          de: 'Land',
          fr: 'Pays',
          pl: 'Kraj',
          cs: 'Země',
        },
        align: 'center',
        renderAs: 'country_flag',
        sortable: true,
        shrink: true,
      },
      {
        name: 'permission_leave',
        field: 'data.permission_leave',
        label: {
          en: 'Leave',
          de: 'Verlassen',
          fr: 'Sortie',
          pl: 'Wyjście',
          cs: 'Opuštění',
        },
        align: 'center',
        renderAs: 'icon_mapping',
        renderOptions: {
          mappings: [
            {
              value: 'alone',
              icon: 'directions_walk',
              color: 'positive',
            },
            {
              value: 'group',
              icon: 'groups',
              color: 'warning',
            },
            {
              value: 'none',
              icon: 'block',
              color: 'negative',
            },
          ],
          fallback: {
            icon: 'question_mark',
            color: 'grey',
          },
        },
        headerVertical: true,
        shrink: true,
      },
      {
        name: 'permission_swim',
        field: 'data.permission_swim',
        label: {
          en: 'No swimming',
          de: 'Nicht schwimmen',
          fr: 'Ne pas nager',
          pl: 'Zakaz pływania',
          cs: 'Nesmí plavat',
        },
        align: 'center',
        renderAs: 'icon',
        renderOptions: {
          name: 'pool',
          color: 'negative',
        },
        showIf: '$data.permission_swim == false',
        headerVertical: true,
        shrink: true,
      },
      {
        name: 'permission_written_consent',
        field: 'data.permission_written_consent',
        label: {
          en: 'No written consent',
          de: 'Keine schriftliche Zustimmung',
          fr: 'Pas d’autorisation écrite',
          pl: 'Brak pisemnej zgody',
          cs: 'Bez písemného souhlasu',
        },
        align: 'center',
        renderAs: 'icon',
        renderOptions: {
          name: 'assignment_late',
          color: 'negative',
        },
        showIf: '$data.permission_written_consent == false',
        headerVertical: true,
        shrink: true,
      },
      {
        name: 'privacy',
        field: 'data.consent_privacy',
        label: {
          en: 'No photos',
          de: 'Keine Fotos',
          fr: 'Pas de photos',
          pl: 'Bez zdjęć',
          cs: 'Žádné fotografie',
        },
        align: 'center',
        renderAs: 'icon',
        renderOptions: {
          name: 'no_photography',
          color: 'negative',
        },
        showIf: '$data.consent_privacy != true',
        headerVertical: true,
        shrink: true,
      },
      {
        name: 'room',
        field: 'room',
        label: {
          en: 'Room',
          de: 'Zimmer',
          fr: 'Chambre',
          pl: 'Pokój',
          cs: 'Pokoj',
        },
        align: 'left',
        renderAs: 'default',
        source: 'meta',
        shrink: true,
      },
    ],
    order: 1,
    filter: "data.role = 'participant'",
    filterStatus: ['ACCEPTED'],
    filterRoles: ['counselor', 'organizer'],
    indexed: true,
    actions: true,
    sortBy: 'first_name',
    id: '01KVH6HQPTFRF2YHHAWBGVSATM',
  },
  {
    title: {
      en: 'Arrival & departure',
      de: 'An- und Abreise',
      fr: 'Arrivée et départ',
      pl: 'Przyjazd i wyjazd',
      cs: 'Příjezd a odjezd',
    },
    columns: [
      {
        name: 'first_name',
        field: 'data.first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          pl: 'Imię',
          cs: 'Jméno',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'last_name',
        field: 'data.last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          pl: 'Nazwisko',
          cs: 'Příjmení',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'country',
        field: 'data.address.country',
        label: {
          en: 'Country',
          de: 'Land',
          fr: 'Pays',
          pl: 'Kraj',
          cs: 'Země',
        },
        align: 'center',
        renderAs: 'country_flag',
        sortable: true,
        shrink: true,
      },
      {
        name: 'arrival',
        field: 'customData.arrival',
        label: {
          en: 'Arrival',
          de: 'Anreise',
          fr: 'Arrivée',
          pl: 'Przyjazd',
          cs: 'Příjezd',
        },
        align: 'left',
        renderAs: 'editor',
        sortable: true,
        source: 'custom',
      },
      {
        name: 'departure',
        field: 'customData.departure',
        label: {
          en: 'Departure',
          de: 'Abreise',
          fr: 'Départ',
          pl: 'Wyjazd',
          cs: 'Odjezd',
        },
        align: 'left',
        renderAs: 'editor',
        sortable: true,
        source: 'custom',
      },
      {
        name: 'travel_notes',
        field: 'customData.travel_notes',
        label: {
          en: 'Travel notes',
          de: 'Reisenotizen',
          fr: 'Notes de voyage',
          pl: 'Notatki podróżne',
          cs: 'Poznámky k cestě',
        },
        align: 'left',
        renderAs: 'editor',
        source: 'custom',
      },
      {
        name: 'permission_leave',
        field: 'data.permission_leave',
        label: {
          en: 'Leave',
          de: 'Verlassen',
          fr: 'Sortie',
          pl: 'Wyjście',
          cs: 'Opuštění',
        },
        align: 'center',
        renderAs: 'icon_mapping',
        renderOptions: {
          mappings: [
            {
              value: 'alone',
              icon: 'directions_walk',
              color: 'positive',
            },
            {
              value: 'group',
              icon: 'groups',
              color: 'warning',
            },
            {
              value: 'none',
              icon: 'block',
              color: 'negative',
            },
          ],
          fallback: {
            icon: 'question_mark',
            color: 'grey',
          },
        },
        headerVertical: true,
        shrink: true,
      },
      {
        name: 'phone_number',
        field: 'data.phone_number',
        label: {
          en: 'Phone',
          de: 'Telefon',
          fr: 'Téléphone',
          pl: 'Telefon',
          cs: 'Telefon',
        },
        align: 'left',
        renderAs: 'phone_number',
      },
      {
        name: 'guardian_email',
        field: 'data.guardian_email',
        label: {
          en: 'Legal guardian e-mail',
          de: 'E-Mail Sorgeberechtigte',
          fr: 'E-mail responsable légal',
          pl: 'E-mail opiekuna prawnego',
          cs: 'E-mail zákonného zástupce',
        },
        align: 'left',
        renderAs: 'email',
      },
    ],
    order: 2,
    filter: "data.role = 'participant'",
    filterStatus: ['ACCEPTED'],
    filterRoles: ['counselor', 'organizer'],
    indexed: true,
    actions: true,
    sortBy: 'first_name',
    id: '01KVH6HQPTA1K8MRPNT7KZX9PE',
  },
  {
    title: {
      en: 'Legal guardians',
      de: 'Sorgeberechtigte',
      fr: 'Responsables légaux',
      pl: 'Opiekunowie prawni',
      cs: 'Zákonní zástupci',
    },
    columns: [
      {
        name: 'first_name',
        field: 'data.first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          pl: 'Imię',
          cs: 'Jméno',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'last_name',
        field: 'data.last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          pl: 'Nazwisko',
          cs: 'Příjmení',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'age',
        field: 'data.date_of_birth',
        label: {
          en: 'Age',
          de: 'Alter',
          fr: 'Âge',
          pl: 'Wiek',
          cs: 'Věk',
        },
        align: 'center',
        renderAs: 'age',
        sortable: true,
        shrink: true,
      },
      {
        name: 'guardian_first_name',
        field: 'data.guardian..first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          pl: 'Imię',
          cs: 'Jméno',
        },
        align: 'left',
        renderAs: 'name',
        isArray: true,
      },
      {
        name: 'guardian_last_name',
        field: 'data.guardian..last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          pl: 'Nazwisko',
          cs: 'Příjmení',
        },
        align: 'left',
        renderAs: 'name',
        isArray: true,
      },
      {
        name: 'guardian_email',
        field: 'data.guardian_email',
        label: {
          en: 'Legal guardian e-mail',
          de: 'E-Mail Sorgeberechtigte',
          fr: 'E-mail responsable légal',
          pl: 'E-mail opiekuna prawnego',
          cs: 'E-mail zákonného zástupce',
        },
        align: 'left',
        renderAs: 'email',
      },
    ],
    order: 3,
    filter: "data.role = 'participant'",
    filterStatus: ['ACCEPTED'],
    filterRoles: ['counselor', 'organizer'],
    indexed: true,
    actions: true,
    sortBy: 'first_name',
    id: '01KVH6HQPTXGPWNDJ141YNRYXF',
  },
  {
    title: {
      en: 'Emergency contacts',
      de: 'Notfallkontakte',
      fr: 'Contacts d’urgence',
      pl: 'Kontakty awaryjne',
      cs: 'Nouzové kontakty',
    },
    columns: [
      {
        name: 'first_name',
        field: 'data.first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          pl: 'Imię',
          cs: 'Jméno',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'last_name',
        field: 'data.last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          pl: 'Nazwisko',
          cs: 'Příjmení',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'age',
        field: 'data.date_of_birth',
        label: {
          en: 'Age',
          de: 'Alter',
          fr: 'Âge',
          pl: 'Wiek',
          cs: 'Věk',
        },
        align: 'center',
        renderAs: 'age',
        sortable: true,
        shrink: true,
      },
      {
        name: 'date_of_birth',
        field: 'data.date_of_birth',
        label: {
          en: 'Date of birth',
          de: 'Geburtsdatum',
          fr: 'Date de naissance',
          pl: 'Data urodzenia',
          cs: 'Datum narození',
        },
        align: 'center',
        renderAs: 'date',
        shrink: true,
      },
      {
        name: 'contact_description',
        field: 'data.emergency_contacts..description',
        label: {
          en: 'Contact',
          de: 'Kontakt',
          fr: 'Contact',
          pl: 'Kontakt',
          cs: 'Kontakt',
        },
        align: 'left',
        renderAs: 'default',
        isArray: true,
      },
      {
        name: 'emergency_phone',
        field: 'data.emergency_contacts..phone_number',
        label: {
          en: 'Phone',
          de: 'Telefon',
          fr: 'Téléphone',
          pl: 'Telefon',
          cs: 'Telefon',
        },
        align: 'left',
        renderAs: 'phone_number',
        isArray: true,
      },
    ],
    order: 4,
    filter: "data.role = 'participant'",
    filterStatus: ['ACCEPTED'],
    filterRoles: ['counselor', 'organizer'],
    indexed: true,
    actions: true,
    sortBy: 'first_name',
    id: '01KVH6HQPTP16H175QMCX0735F',
  },
  {
    title: {
      en: 'Health & nutrition',
      de: 'Gesundheit & Ernährung',
      fr: 'Santé et alimentation',
      pl: 'Zdrowie i odżywianie',
      cs: 'Zdraví a výživa',
    },
    columns: [
      {
        name: 'first_name',
        field: 'data.first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          pl: 'Imię',
          cs: 'Jméno',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'last_name',
        field: 'data.last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          pl: 'Nazwisko',
          cs: 'Příjmení',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'medical_restrictions',
        field: 'data.medical_restrictions',
        label: {
          en: 'Medical restrictions',
          de: 'Medizinische Einschränkungen',
          fr: 'Restrictions médicales',
          pl: 'Ograniczenia medyczne',
          cs: 'Zdravotní omezení',
        },
        align: 'left',
        renderAs: 'text',
      },
      {
        name: 'food_intolerance',
        field: 'data.food_intolerance',
        label: {
          en: 'Special nutrition',
          de: 'Besondere Ernährung',
          fr: 'Alimentation spéciale',
          pl: 'Specjalna dieta',
          cs: 'Speciální strava',
        },
        align: 'left',
        renderAs: 'text',
      },
      {
        name: 'additional_information',
        field: 'data.additional_information',
        label: {
          en: 'Additional information',
          de: 'Weitere Informationen',
          fr: 'Informations supplémentaires',
          pl: 'Dodatkowe informacje',
          cs: 'Další informace',
        },
        align: 'left',
        renderAs: 'text',
      },
      {
        name: 'permission_swim',
        field: 'data.permission_swim',
        label: {
          en: 'No swimming',
          de: 'Nicht schwimmen',
          fr: 'Ne pas nager',
          pl: 'Zakaz pływania',
          cs: 'Nesmí plavat',
        },
        align: 'center',
        renderAs: 'icon',
        renderOptions: {
          name: 'pool',
          color: 'negative',
        },
        showIf: '$data.permission_swim == false',
        headerVertical: true,
        shrink: true,
      },
      {
        name: 'permission_written_consent',
        field: 'data.permission_written_consent',
        label: {
          en: 'No written consent',
          de: 'Keine schriftliche Zustimmung',
          fr: 'Pas d’autorisation écrite',
          pl: 'Brak pisemnej zgody',
          cs: 'Bez písemného souhlasu',
        },
        align: 'center',
        renderAs: 'icon',
        renderOptions: {
          name: 'assignment_late',
          color: 'negative',
        },
        showIf: '$data.permission_written_consent == false',
        headerVertical: true,
        shrink: true,
      },
    ],
    order: 5,
    filter: "data.role = 'participant'",
    filterStatus: ['ACCEPTED'],
    filterRoles: ['counselor', 'organizer'],
    indexed: true,
    actions: true,
    sortBy: 'first_name',
    id: '01KVH6HQPT4H7RE4HWXNG6JYD4',
  },
  {
    title: {
      en: 'Consents',
      de: 'Zustimmungen',
      fr: 'Consentements',
      pl: 'Zgody',
      cs: 'Souhlasy',
    },
    columns: [
      {
        name: 'first_name',
        field: 'data.first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          pl: 'Imię',
          cs: 'Jméno',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'last_name',
        field: 'data.last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          pl: 'Nazwisko',
          cs: 'Příjmení',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'consent_rules',
        field: 'data.consent_rules',
        label: {
          en: 'Rules missing',
          de: 'Regeln fehlen',
          fr: 'Règlement manquant',
          pl: 'Brak regulaminu',
          cs: 'Chybí pravidla',
        },
        align: 'center',
        renderAs: 'icon',
        renderOptions: {
          name: 'gavel',
          color: 'negative',
        },
        showIf: '$data.consent_rules != true',
        headerVertical: true,
        shrink: true,
      },
      {
        name: 'consent_terms',
        field: 'data.consent_general_terms_and_conditions',
        label: {
          en: 'Terms missing',
          de: 'AGB fehlen',
          fr: 'Conditions manquantes',
          pl: 'Brak warunków',
          cs: 'Chybí podmínky',
        },
        align: 'center',
        renderAs: 'icon',
        renderOptions: {
          name: 'description',
          color: 'negative',
        },
        showIf: '$data.consent_general_terms_and_conditions != true',
        headerVertical: true,
        shrink: true,
      },
      {
        name: 'confirmation_guardian',
        field: 'data.confirmation_guardian',
        label: {
          en: 'Guardian missing',
          de: 'Sorgeberechtigte:r fehlt',
          fr: 'Responsable légal manquant',
          pl: 'Brak opiekuna prawnego',
          cs: 'Chybí zákonný zástupce',
        },
        align: 'center',
        renderAs: 'icon',
        renderOptions: {
          name: 'family_restroom',
          color: 'negative',
        },
        showIf: '$data.confirmation_guardian != true',
        headerVertical: true,
        shrink: true,
      },
      {
        name: 'consent_privacy',
        field: 'data.consent_privacy',
        label: {
          en: 'No photos',
          de: 'Keine Fotos',
          fr: 'Pas de photos',
          pl: 'Bez zdjęć',
          cs: 'Žádné fotografie',
        },
        align: 'center',
        renderAs: 'icon',
        renderOptions: {
          name: 'no_photography',
          color: 'negative',
        },
        showIf: '$data.consent_privacy != true',
        headerVertical: true,
        shrink: true,
      },
      {
        name: 'consent_forward_list_participants',
        field: 'data.consent_forward_list_participants',
        label: {
          en: 'Carpool list',
          de: 'Fahrgemeinschaftsliste',
          fr: 'Liste covoiturage',
          pl: 'Lista wspólnych przejazdów',
          cs: 'Seznam pro spolujízdu',
        },
        align: 'center',
        renderAs: 'icon',
        renderOptions: {
          name: 'directions_car',
          color: 'positive',
        },
        showIf: '$data.consent_forward_list_participants == true',
        headerVertical: true,
        shrink: true,
      },
      {
        name: 'newsletter',
        field: 'data.newsletter',
        label: {
          en: 'Newsletter',
          de: 'Newsletter',
          fr: 'Newsletter',
          pl: 'Newsletter',
          cs: 'Newsletter',
        },
        align: 'center',
        renderAs: 'icon',
        renderOptions: {
          name: 'mark_email_read',
          color: 'positive',
        },
        showIf: '$data.newsletter == true',
        headerVertical: true,
        shrink: true,
      },
    ],
    order: 6,
    filter: "data.role = 'participant'",
    filterStatus: ['ACCEPTED'],
    filterRoles: ['counselor', 'organizer'],
    indexed: true,
    actions: true,
    sortBy: 'first_name',
    id: '01KVH6HQPT0AKMAD5AX1FZMHH0',
  },
  {
    title: {
      en: 'Payments',
      de: 'Zahlungen',
      fr: 'Paiements',
      pl: 'Płatności',
      cs: 'Platby',
    },
    columns: [
      {
        name: 'first_name',
        field: 'data.first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          pl: 'Imię',
          cs: 'Jméno',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'last_name',
        field: 'data.last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          pl: 'Nazwisko',
          cs: 'Příjmení',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'country',
        field: 'data.address.country',
        label: {
          en: 'Country',
          de: 'Land',
          fr: 'Pays',
          pl: 'Kraj',
          cs: 'Země',
        },
        align: 'center',
        renderAs: 'country_flag',
        sortable: true,
        shrink: true,
      },
      {
        name: 'status',
        field: 'status',
        label: {
          en: 'Status',
          de: 'Status',
          fr: 'Statut',
          pl: 'Status',
          cs: 'Stav',
        },
        align: 'center',
        renderAs: 'status',
        sortable: true,
        shrink: true,
      },
      {
        name: 'participation_fee_paid',
        field: 'customData.participation_fee_paid',
        label: {
          en: 'Participation fee',
          de: 'Teilnahmebeitrag',
          fr: 'Frais de participation',
          pl: 'Opłata za udział',
          cs: 'Účastnický poplatek',
        },
        align: 'center',
        renderAs: 'editor',
        sortable: true,
        source: 'custom',
      },
      {
        name: 'payment_note',
        field: 'customData.payment_note',
        label: {
          en: 'Payment note',
          de: 'Zahlungsnotiz',
          fr: 'Note de paiement',
          pl: 'Notatka płatności',
          cs: 'Poznámka k platbě',
        },
        align: 'left',
        renderAs: 'editor',
        source: 'custom',
      },
    ],
    order: 7,
    filter: "data.role = 'participant'",
    filterStatus: ['ACCEPTED'],
    filterRoles: ['organizer'],
    indexed: true,
    actions: true,
    sortBy: 'first_name',
    id: '01KVH6HQPTMF01N8YBNGE1VKGX',
  },
  {
    title: {
      en: 'Carpool contact list',
      de: 'Kontaktliste Fahrgemeinschaften',
      fr: 'Liste de contacts covoiturage',
      pl: 'Lista kontaktów do wspólnych przejazdów',
      cs: 'Seznam kontaktů pro spolujízdu',
    },
    columns: [
      {
        name: 'first_name',
        field: 'data.first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          pl: 'Imię',
          cs: 'Jméno',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'last_name',
        field: 'data.last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          pl: 'Nazwisko',
          cs: 'Příjmení',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'country',
        field: 'data.address.country',
        label: {
          en: 'Country',
          de: 'Land',
          fr: 'Pays',
          pl: 'Kraj',
          cs: 'Země',
        },
        align: 'center',
        renderAs: 'country_flag',
        sortable: true,
        shrink: true,
      },
      {
        name: 'phone_number',
        field: 'data.phone_number',
        label: {
          en: 'Phone',
          de: 'Telefon',
          fr: 'Téléphone',
          pl: 'Telefon',
          cs: 'Telefon',
        },
        align: 'left',
        renderAs: 'phone_number',
      },
      {
        name: 'email',
        field: 'data.email',
        label: {
          en: 'E-mail',
          de: 'E-Mail',
          fr: 'E-mail',
          pl: 'E-mail',
          cs: 'E-mail',
        },
        align: 'left',
        renderAs: 'email',
      },
      {
        name: 'address',
        field: 'data.address',
        label: {
          en: 'Address',
          de: 'Adresse',
          fr: 'Adresse',
          pl: 'Adres',
          cs: 'Adresa',
        },
        align: 'left',
        renderAs: 'address',
      },
    ],
    order: 8,
    filter:
      "data.role = 'participant' and data.consent_forward_list_participants = true",
    filterStatus: ['ACCEPTED'],
    filterRoles: ['participant', 'counselor', 'organizer'],
    indexed: true,
    actions: false,
    sortBy: 'first_name',
    id: '01KVH6HQPTH0PFJKQ0K4W6JJWX',
  },
  {
    title: {
      en: 'Team',
      de: 'Team',
      fr: 'Équipe',
      pl: 'Kadra',
      cs: 'Tým',
    },
    columns: [
      {
        name: 'first_name',
        field: 'data.first_name',
        label: {
          en: 'First name',
          de: 'Vorname',
          fr: 'Prénom',
          pl: 'Imię',
          cs: 'Jméno',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'last_name',
        field: 'data.last_name',
        label: {
          en: 'Last name',
          de: 'Nachname',
          fr: 'Nom de famille',
          pl: 'Nazwisko',
          cs: 'Příjmení',
        },
        align: 'left',
        renderAs: 'name',
        sortable: true,
      },
      {
        name: 'role',
        field: 'data.role',
        label: {
          en: 'Role',
          de: 'Rolle',
          fr: 'Rôle',
          pl: 'Rola',
          cs: 'Role',
        },
        align: 'center',
        renderAs: 'default',
        sortable: true,
        shrink: true,
      },
      {
        name: 'age',
        field: 'data.date_of_birth',
        label: {
          en: 'Age',
          de: 'Alter',
          fr: 'Âge',
          pl: 'Wiek',
          cs: 'Věk',
        },
        align: 'center',
        renderAs: 'age',
        sortable: true,
        shrink: true,
      },
      {
        name: 'country',
        field: 'data.address.country',
        label: {
          en: 'Country',
          de: 'Land',
          fr: 'Pays',
          pl: 'Kraj',
          cs: 'Země',
        },
        align: 'center',
        renderAs: 'country_flag',
        sortable: true,
        shrink: true,
      },
      {
        name: 'email',
        field: 'data.email',
        label: {
          en: 'E-mail',
          de: 'E-Mail',
          fr: 'E-mail',
          pl: 'E-mail',
          cs: 'E-mail',
        },
        align: 'left',
        renderAs: 'email',
      },
      {
        name: 'phone_number',
        field: 'data.phone_number',
        label: {
          en: 'Phone',
          de: 'Telefon',
          fr: 'Téléphone',
          pl: 'Telefon',
          cs: 'Telefon',
        },
        align: 'left',
        renderAs: 'phone_number',
      },
      {
        name: 'address',
        field: 'data.address',
        label: {
          en: 'Address',
          de: 'Adresse',
          fr: 'Adresse',
          pl: 'Adres',
          cs: 'Adresa',
        },
        align: 'left',
        renderAs: 'address',
        shrink: true,
      },
      {
        name: 'additional_information',
        field: 'data.additional_information',
        label: {
          en: 'Additional information',
          de: 'Weitere Informationen',
          fr: 'Informations supplémentaires',
          pl: 'Dodatkowe informacje',
          cs: 'Další informace',
        },
        align: 'left',
        renderAs: 'text',
        shrink: true,
      },
    ],
    order: 9,
    filter: "data.role <> 'participant'",
    filterStatus: ['ACCEPTED'],
    filterRoles: ['counselor', 'organizer'],
    indexed: true,
    actions: true,
    sortBy: 'first_name',
    id: '01KVH6HQPT19QEZAJR1KZWPYHM',
  },
];
